spring.application.name=fegin-client-demo
server.servlet.context-path=/feign-client

logging.level.com.feginClientDemo=DEBUG
logging.level.com.feginClientDemo.feignclient.UserClient= DEBUG

spring.cloud.openfeign.client.config.demo.loggerLevel=full
spring.cloud.openfeign.client.config.default.loggerLevel=full
